#GPIO SUPPORT
CONFIG_GPIO=y

#LOG SUPPORT

CONFIG_LOG=y

# Floating Point Unit
CONFIG_FPU=y

# Increase stack size for the main thread and System Workqueue
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
CONFIG_MAIN_STACK_SIZE=2048

#---------------------------------------------------------------------------------------------------------------
#BLE stack

#Enable
#By default broadcast support is enabled, BT_LL_CHOICE = BT_LL_SOFTDEVICE, BT_CTLR_TX_PWR = BT_CTLR_TX_PWR_0
#Zephyr automatically handles the finding of the radio HW from the dtsi
CONFIG_BT=y

#Enable security management protocol
CONFIG_BT_SMP=y
CONFIG_BT_BONDABLE=y

#Device name
CONFIG_BT_DEVICE_NAME="ZEPHYR SANDBOX"

#Support for peripheral role
#Enable functionalities for peripheral role, including GATT and ATT
#Default number for simultaneous connections is 1
CONFIG_BT_PERIPHERAL=y


#Change prefered connection parameters 
CONFIG_BT_GAP_AUTO_UPDATE_CONN_PARAMS=y
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=800
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=800
CONFIG_BT_PERIPHERAL_PREF_LATENCY=0
CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=400

#Enable GATT server
CONFIG_BT_GATT_DM=y 

#---------------------------------------------------------------------------------------------------------------
